# Generated by Django 5.1 on 2024-08-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0005_remove_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
