# Generated by Django 5.1 on 2024-09-18 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_app', '0011_warehouse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
